name: build

on: push

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - name: source
      run: |
        sh download.sh
        mkdir -p $HOME/data/src
        mv *.orig.tar.gz $HOME/data/src
    - name: setup
      run: |
        sudo apt-get update
        sudo apt-get -y install cdbs devscripts quilt reprepro cmake
        sh setup.sh
    - name: build
      run: |
        sh build.sh
        ls -lR $HOME/data/pkg
