name: build

on: push

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - name: source
      run: |
        sh download.sh
        mkdir -p $HOME/data/src
        mv *.orig.tar.gz $HOME/data/src
    - name: setup
      run: |
        sudo apt-get update
        sudo apt-get -y install cdbs devscripts quilt reprepro cmake
        mkdir build
        cd build
        sh ../setup.sh
    - name: build
      run: |
        pwd
        ls
        cd build
        pwd
        ls
        dpkg-buildpackage -us -uc
        ls ..
